from datetime import datetime, timezone
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field


class ConversationIntent(str, Enum):
    """Categorized intent for learner conversational queries."""

    GOAL_STATUS = "GOAL_STATUS"
    SKILL_STATUS = "SKILL_STATUS"
    BOTTLENECK_EXPLANATION = "BOTTLENECK_EXPLANATION"
    NEXT_ACTION_EXPLANATION = "NEXT_ACTION_EXPLANATION"
    PATH_EXPLANATION = "PATH_EXPLANATION"
    PROGRESS_SUMMARY = "PROGRESS_SUMMARY"
    EVIDENCE_QUERY = "EVIDENCE_QUERY"
    UNCERTAINTY_QUERY = "UNCERTAINTY_QUERY"
    SKILL_HISTORY = "SKILL_HISTORY"
    REPLAN_EXPLANATION = "REPLAN_EXPLANATION"
    COMPARISON = "COMPARISON"
    GENERAL_LEARNING_QUERY = "GENERAL_LEARNING_QUERY"
    UNSUPPORTED = "UNSUPPORTED"


class SourceType(str, Enum):
    """Authoritative application data source types."""

    GOAL = "GOAL"
    ROLE_REQUIREMENT = "ROLE_REQUIREMENT"
    SKILL_MASTERY = "SKILL_MASTERY"
    SKILL_EVIDENCE = "SKILL_EVIDENCE"
    MASTERY_OUTCOME = "MASTERY_OUTCOME"
    BOTTLENECK_ANALYSIS = "BOTTLENECK_ANALYSIS"
    NEXT_ACTION = "NEXT_ACTION"
    LEARNING_PATH = "LEARNING_PATH"
    PATH_DIFF = "PATH_DIFF"
    PROGRESS = "PROGRESS"
    LEARNING_ACTIVITY = "LEARNING_ACTIVITY"


class SourceReference(BaseModel):
    """Structured reference linking a claim to an authoritative application record."""

    model_config = ConfigDict(from_attributes=True)

    source_type: SourceType
    source_id: str
    label: str


class ClaimItem(BaseModel):
    """Grounded factual claim extracted from authoritative application state."""

    model_config = ConfigDict(from_attributes=True)

    claim: str
    source_ids: list[str] = Field(default_factory=list)


class GroundedAnswer(BaseModel):
    """Structured response model generated by LLM / Conversational Engine."""

    model_config = ConfigDict(from_attributes=True)

    intent: ConversationIntent
    response_type: str = "LEARNER_GROUNDED_RESPONSE"  # LEARNER_GROUNDED_RESPONSE, GENERAL_LEARNING_RESPONSE, UNSUPPORTED_RESPONSE, ERROR_RESPONSE
    answer: str
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    claims: list[ClaimItem] = Field(default_factory=list)
    sources: list[SourceReference] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    suggested_followups: list[str] = Field(default_factory=list)


class CreateSessionRequest(BaseModel):
    """Payload for creating a new conversation session."""

    learner_id: UUID
    title: str | None = None


class SessionResponse(BaseModel):
    """Summary representation of a conversation session."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    learner_id: UUID
    title: str
    created_at: datetime
    updated_at: datetime


class SendMessageRequest(BaseModel):
    """Payload for sending a user message to a conversation session."""

    learner_id: UUID
    message: str = Field(..., min_length=1, max_length=1000)


class MessageResponse(BaseModel):
    """Response payload for a message in a conversation session."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    role: str  # user, assistant, system
    content: str
    intent: ConversationIntent | None = None
    confidence: float | None = None
    response_type: str = "LEARNER_GROUNDED_RESPONSE"
    sources: list[SourceReference] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    suggested_followups: list[str] = Field(default_factory=list)
    used_llm: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SessionDetailResponse(BaseModel):
    """Detailed view of a conversation session including message history."""

    model_config = ConfigDict(from_attributes=True)

    session: SessionResponse
    messages: list[MessageResponse] = Field(default_factory=list)
