"""add_diagnostic_tables

Revision ID: 2def2ae295f4
Revises: b3262531abe9
Create Date: 2026-08-26 15:22:41.052539

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2def2ae295f4"
down_revision: Union[str, Sequence[str], None] = "b3262531abe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnostic_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_skill_id", sa.UUID(), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("max_questions", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["current_skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_sessions_goal_id"), "diagnostic_sessions", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_sessions_learner_id"),
        "diagnostic_sessions",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "diagnostic_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("learner_answer", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("evaluation_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["assessment_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["diagnostic_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_responses_idempotency_key"),
        "diagnostic_responses",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_diagnostic_responses_question_id"),
        "diagnostic_responses",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_responses_session_id"),
        "diagnostic_responses",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnostic_responses_session_id"), table_name="diagnostic_responses")
    op.drop_index(op.f("ix_diagnostic_responses_question_id"), table_name="diagnostic_responses")
    op.drop_index(
        op.f("ix_diagnostic_responses_idempotency_key"), table_name="diagnostic_responses"
    )
    op.drop_table("diagnostic_responses")
    op.drop_index(op.f("ix_diagnostic_sessions_learner_id"), table_name="diagnostic_sessions")
    op.drop_index(op.f("ix_diagnostic_sessions_goal_id"), table_name="diagnostic_sessions")
    op.drop_table("diagnostic_sessions")
    # ### end Alembic commands ###
