"""add_skill_relation_unique_constraint

Revision ID: 7144135658a4
Revises: c27eb12bdd49
Create Date: 2026-08-26 15:00:52.191025

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7144135658a4"
down_revision: Union[str, Sequence[str], None] = "c27eb12bdd49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_skill_relation",
        "skill_relations",
        [
            "source_skill_id",
            "target_skill_id",
            "relation_type",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_skill_relation", "skill_relations", type_="unique")
    # ### end Alembic commands ###
