"""remove duplicate unique constraints on user_accounts

Revision ID: 91c7ac064202
Revises: d8f912c34e56
Create Date: 2026-08-30 17:27:50.931071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c7ac064202'
down_revision: Union[str, Sequence[str], None] = 'd8f912c34e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_accounts_email_key'), 'user_accounts', type_='unique')
    op.drop_constraint(op.f('user_accounts_learner_id_key'), 'user_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_accounts_learner_id_key'), 'user_accounts', ['learner_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_accounts_email_key'), 'user_accounts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
