"""add_learner_profile_table

Revision ID: b3262531abe9
Revises: 7144135658a4
Create Date: 2026-08-26 15:05:57.951164

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3262531abe9"
down_revision: Union[str, Sequence[str], None] = "7144135658a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learner_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("experience_level", sa.String(length=50), nullable=True),
        sa.Column("preferred_learning_mode", sa.String(length=50), nullable=True),
        sa.Column("weekly_availability_hours", sa.Float(), nullable=True),
        sa.Column("stated_background", sa.Text(), nullable=True),
        sa.Column("profile_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learner_profiles_learner_id"),
        "learner_profiles",
        ["learner_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learner_profiles_learner_id"), table_name="learner_profiles")
    op.drop_table("learner_profiles")
    # ### end Alembic commands ###
