"""initial_phase2_domain_schema

Revision ID: c27eb12bdd49
Revises:
Create Date: 2026-08-26 14:50:47.081169

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c27eb12bdd49"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learners",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learners_email"), "learners", ["email"], unique=True)
    op.create_table(
        "learning_resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("parent_skill_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_index(op.f("ix_skills_parent_skill_id"), "skills", ["parent_skill_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("assessment_type", sa.String(length=50), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assessments_skill_id"), "assessments", ["skill_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("target_role_id", sa.UUID(), nullable=False),
        sa.Column("objective", sa.String(length=200), nullable=False),
        sa.Column("timeline_weeks", sa.Integer(), nullable=True),
        sa.Column("daily_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_learner_id"), "goals", ["learner_id"], unique=False)
    op.create_index(op.f("ix_goals_target_role_id"), "goals", ["target_role_id"], unique=False)
    op.create_table(
        "role_skills",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("required_level", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "skill_id"),
    )
    op.create_table(
        "skill_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_evidence_learner_id"),
        "skill_evidence",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_evidence_skill_id"), "skill_evidence", ["skill_id"], unique=False
    )
    op.create_table(
        "skill_mastery",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "skill_id", name="uq_learner_skill_mastery"),
    )
    op.create_index(
        op.f("ix_skill_mastery_learner_id"),
        "skill_mastery",
        ["learner_id"],
        unique=False,
    )
    op.create_index(op.f("ix_skill_mastery_skill_id"), "skill_mastery", ["skill_id"], unique=False)
    op.create_table(
        "skill_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_skill_id", sa.UUID(), nullable=False),
        sa.Column("target_skill_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_relations_source_skill_id"),
        "skill_relations",
        ["source_skill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_relations_target_skill_id"),
        "skill_relations",
        ["target_skill_id"],
        unique=False,
    )
    op.create_table(
        "skill_resources",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["learning_resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("skill_id", "resource_id"),
    )
    op.create_table(
        "assessment_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("expected_answer", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_questions_assessment_id"),
        "assessment_questions",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_questions_skill_id"),
        "assessment_questions",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("expected_readiness", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learning_paths_goal_id"), "learning_paths", ["goal_id"], unique=False)
    op.create_index(
        op.f("ix_learning_paths_learner_id"),
        "learning_paths",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "learning_path_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learning_path_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("milestone_label", sa.String(length=120), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["learning_path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["learning_resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learning_path_id", "sequence", name="uq_path_node_sequence"),
    )
    op.create_index(
        op.f("ix_learning_path_nodes_learning_path_id"),
        "learning_path_nodes",
        ["learning_path_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_path_nodes_resource_id"),
        "learning_path_nodes",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_path_nodes_skill_id"),
        "learning_path_nodes",
        ["skill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_path_nodes_skill_id"), table_name="learning_path_nodes")
    op.drop_index(op.f("ix_learning_path_nodes_resource_id"), table_name="learning_path_nodes")
    op.drop_index(
        op.f("ix_learning_path_nodes_learning_path_id"),
        table_name="learning_path_nodes",
    )
    op.drop_table("learning_path_nodes")
    op.drop_index(op.f("ix_learning_paths_learner_id"), table_name="learning_paths")
    op.drop_index(op.f("ix_learning_paths_goal_id"), table_name="learning_paths")
    op.drop_table("learning_paths")
    op.drop_index(op.f("ix_assessment_questions_skill_id"), table_name="assessment_questions")
    op.drop_index(op.f("ix_assessment_questions_assessment_id"), table_name="assessment_questions")
    op.drop_table("assessment_questions")
    op.drop_table("skill_resources")
    op.drop_index(op.f("ix_skill_relations_target_skill_id"), table_name="skill_relations")
    op.drop_index(op.f("ix_skill_relations_source_skill_id"), table_name="skill_relations")
    op.drop_table("skill_relations")
    op.drop_index(op.f("ix_skill_mastery_skill_id"), table_name="skill_mastery")
    op.drop_index(op.f("ix_skill_mastery_learner_id"), table_name="skill_mastery")
    op.drop_table("skill_mastery")
    op.drop_index(op.f("ix_skill_evidence_skill_id"), table_name="skill_evidence")
    op.drop_index(op.f("ix_skill_evidence_learner_id"), table_name="skill_evidence")
    op.drop_table("skill_evidence")
    op.drop_table("role_skills")
    op.drop_index(op.f("ix_goals_target_role_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_learner_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_assessments_skill_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_skills_parent_skill_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("learning_resources")
    op.drop_index(op.f("ix_learners_email"), table_name="learners")
    op.drop_table("learners")
    # ### end Alembic commands ###
